### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by Liberater** [Kaiserreich/Kaiserreich-DH#30]
Hello I'm not sure if its just me but the mod seems to crash while loading after country select but only once it reaches the very end of the loading bar

**Comment by eberronguy** [comment]
Thank you for pointing that out. We had it fixed but I forgot to push the fix to the master. It should be done now, please keep me posted if there are any problems. If there are see what save debug says.

**Comment by Liberater** [comment]
> Thank you for pointing that out. We had it fixed but I forgot to push the fix to the master. It should be done now, please keep me posted if there are any problems. If there are see what save debug says.

thanks works fine now
