### ISSUE TITLE
Venezuela 1939 elections do not fire.

### ISSUE THREAD

**Issue by TheBoySuru** [Kaiserreich/Kaiserreich-DH#32]
I have been playing Venezuela quite lately because of the update, Gran Colombia was surely a great addition to the mod (you guys could try harder and make a Latin American Union Nation C:) and well, I have played it with the temporary junta usually.

*I have made it to the election date without starting war, elections did not fire.
*I have made it to the election date as Gran Colombia, elections did not fire.
*Also did it with the social democrat government intact, still, elections did not fire.

I also never really change the government type through policies, I do all the events I can, like, I do not miss a single event of Venezuela, hell, I actually got mad at the fact that the "Navy doctrine re-evaluation" can not be done if you get the "expanding weapons industry", MAN, THERE ARE LIKE 5 EVENTS WITH THE SAME NAME (on top of that, the whole navy doctrine tree is useless, Venezuela starts off with Fleet in the being tree already).

I am not sure if I should post a pic, since it is not something that happens from time to time, ELECTIONS NEVER FIRE and one must be stuck with the shitty Head of States that Eleazar and his partner are.

The only thing I have not tried is delaying events, I always rush them ASAP, but I do not think that should be problematic at all as I noticed that 1939 is its own tree of events.

**Comment by eberronguy** [comment]
Fixed the errors for the election. It was a case of a line in the code making Venezuela be democratic to have the elections. One prewar path is not democratic by DH standards so it was not firing.
