### ISSUE TITLE
Syndicalist Pacific States joining Canada

### ISSUE THREAD

**Issue by BlaneckW** [Kaiserreich/Kaiserreich-DH#33]
Hey, this wouldn't probably be hard to fix, even if there isn't any events for a Syndicalist Pacific States (I didn't check), if I puppet it and release it (say, as Commune of France), you could set it so it doesn't join Canada if it's Syndicalist (or Totalist, whatever). Unless you wanted to program a coup that did that, I suppose (there wasn't).

**Comment by eberronguy** [comment]
Thank you for the suggestion. Added, and also added the same condition to its other allies, since neither Germany or Japan want syndicalist allies.
