### ISSUE TITLE
Mindaugas III and his government taking over Japan?

### ISSUE THREAD

**Issue by nario308** [Kaiserreich/Kaiserreich-DH#39]
Hello, 
I was playing with the latest version of the mod as democratic Japan (Defend democracy/Electoral reform, etc.) keeping the Seiyukai at power, without interfering with the europeans alliances (staying in the co-prosperity sphere), until 1:00, 2 Dec, 1941, when an event (lithuania.12) triggered:

![Bug Mindaugas Japan Kaiserreich](https://user-images.githubusercontent.com/65444068/82116156-df2e4a80-9767-11ea-982c-93be7603f999.png)

It kept my government party as the Seiyaku, stopped the elections (the lastest ones were in 1940 and the next supposed to be in 1944), and put Mindaugas III (leader of Lithuania) at the head of government (replacing Hirohito), and adding a government that is composed of Lithuanian people.
I never played as Lithuania before playing Japan, nor changed with the tag command for cheats, so I have no idea how this can be happening. All the cheats I used in the game were teleport or deleteallunits, but never did it on Lithuania or any Reichspakt member.

![Bug Mindaugas Japan Kaiserreich_1](https://user-images.githubusercontent.com/65444068/82116163-ebb2a300-9767-11ea-919b-d7e2a28f4236.png)

Thanks for reading this report, and thanks for everything you do developing this mod, and sorry if I trouble you with a bug that I will ever be the only one to have.

(That is my first time posting in github, so i'm sorry if I don't respect the layout or something)

**Comment by eberronguy** [comment]
Please never feel bad about reporting a bug, as bugs must be squashed no matter how obscure they may be.

That being said you are in the wrong git. This is for Kaiserreich for Darkest Hour, not Kaiserreich for Hearts of Iron 4. Although I actively help with both mods I am not the person able to fix this at this time. I will redirect you to make a bug report here:

https://github.com/Kaiserreich/Kaiserreich-4/issues

Please double check before posting that someone has not already reported this, and thank you very much for reporting the bug. Have a wonderful day!
