### ISSUE TITLE
several

### ISSUE THREAD

**Issue by dhkrbugreport** [Kaiserreich/Kaiserreich-DH#44]
1) when qing starts the manchuria events, there is option for fengtian to abandon japan for qing. however this event does not result in fengtian allying with qing. fengtian leaves alliance with japan and is still at war with qing (in war against qing together with japan).

2)azerbaijan probably should have cores on tabriz and rezaiye(sp?) (the province of persia bordering ottomans). these regions are azerbaijani populated heavily. even today you go there and you see nobody speak persian but all speak azerbaijani. OTL separatist movements also existed back then and do exist now.

3)when germany invite national france in exchange for land, and france accepts, germany will keep getting "return french land" event because of alsace - lorraine. probably because event checks for france region?

4)austrian event for imposing austrian king on italy, if italy loses and makes peace in the war via event the pope still stays as head of state. and even though puppet italy will not accept alliance offer (probably because of pope?)

5)perhaps add ottomans/turkey cores in balkans? idk i think once there was events for cores if you conquer bulgaria... but should be/could be cores for till salonika at least. and plus one bulgaria province... maybe tie it to the balkan war?

**Comment by Maxian25** [comment]
Working on a couple bugs:
1) I put leave_alliance commands in these events so hopefully they'll work more correctly next release.
2) Done.
3) I suspect the cause was event 130000 in 'National France.txt'. Removed GER from allowable tag.
