### ISSUE TITLE
ACW II Limbo

### ISSUE THREAD

**Issue by Wendigo326** [Kaiserreich/Kaiserreich-DH#47]
The second ACW event chain goes into limbo if you do the following:

Elect the Democrats, negotiate with Reed, implement his reforms, back down from the reforms, Expel Long, declare martial law.

I waited until 1938 to see if anything more happened and it seems event ID 800127 in USA.txt does not fire, or will fire at some point between 1938 and 1947.

**Comment by eberronguy** [comment]
I apologize for the delay in responding, but it looks like you got unlucky after a test I just ran. 

If anything further comes up please feel free to reach out.
