### ISSUE TITLE
A Bunch of PSA Issues & More

### ISSUE THREAD

**Issue by KiitaSpetOfGermania** [Kaiserreich/Kaiserreich-DH#49]
_**Preamble:**_ I have played PSA a lot, since 0.7 onward. I have been through the highs and lows of USA development, and greatly applaud the work of the dev team on North America; it is my favorite region for a reason! That being said, the most recent update (0.16) has borked my favorite 2AWC faction beyond belief. Combined with several other things I've noticed from months of PSA campaigns, I have collected a list of three types of issues:
1) Major gameplay issues, which are objectively harming the gameplay and tertiary enjoyment of PSA.
2) Minor Gripes/Inconsistencies/etc, which are a bunch of things which I feel many other PSA players have also experienced.
3) Personal suggestions, which are a bunch of minor tweaks and/or additions which would greatly help PSA's performance. This being the most subjective section, I do not mind if none of it is addressed.

Also, please note that this is my first real git issue report, so I apologize if this is formatted incorrectly or otherwise inappropriate. Save games at bottom.

_**Major Gameplay Issues (Eg: Objective, major issues as of last patch):**_

**-You cannot fight rebels or reduce resistance. You do not have a decision to fight rebels or reduce their impact as of the latest update.** Picture attached: ![image_2021-01-18_224927](https://user-images.githubusercontent.com/77653179/104985637-6ad73580-59df-11eb-82c3-2a7c4ab54a11.png)
**-You do not get access to the reconstruction national spirit. Combined with being unable to fight rebels, you are at a severe disadvantage on factory repair compared to all other factions.** PSA should have one of the hardest civil wars in exchange for one of the easiest reconstructions (opposite of CSA).
-PSA only has one air branch. Compared to other factions with a mean of two, this locks the PSA into one effective strategy/doctrine.
-Howard Hughes aircraft event does not fire anymore. Additionally, special presidential events like this one (or Henry Wallace’s) should fire sooner.

_**Minor Gripes/Inconsistencies/Problems:**_

-**A player-led PSA does not start with Nevada unless WP Yorkshire is done, while AI PSA starts with Nevada. You should also be able to choose which War Plan White you would like to do BEFORE switching to PSA.**
-**Some PSA tanks, Improved Infantry Equipment I-III, Infantry Anti-Tank I-II, Night Vision I-II, and (support) Weapons IV have no flavor, be it in name, image or description. (The biggest offender is Armored)**
-**Frank Merriam is unelectable in 1937.** Unsure if this is an intentional change, but it shouldn’t be. The governor of the largest state w/ the largest party popularity who spearheaded the rebellion in the first place should unconditionally be on the ballot.
-First Progressive/F-L flavor event should boost party popularity. Both their popularities should start out lower. (Like CSA interwar events dictating party popularity, for example).
-Frank Merriam, Howard Hughes, Culbert Olsen, Charles Sprague, Ralph Lawrence Carr, and Arthur B Langlie have weirdly lo-fi portraits. Like old Garner, should be touched up.
-Glen Taylor (1948), George N Craig, and Harry Cain all have bugged/missing portraits. Cain and 1948 McKay are missing bios.
-**Merriam, Lee, and Peterson have incorrect party information in their bios; among others. For ex, they are referred to as Republicans (like they were OTL), but are Democrats in game.**
-AUS gets USA event without NEE, but PSA needs NEE for USA event to fire.
-I find it unrealistic that after 1940, majority of major party candidates are still from west of the Mississippi. Flavor choice? Understandable. But where is my PSA Dewey?
-AUS should get a unification path with PSA, like how CSA gets one w/ SocDem PSA. Maybe w/ failed business plot and SocCon PSA?
-PSA should gain slightly more political power.

_**Suggestions/Additions (Optional, totally unnecessary changes to be considered):**_

-A more liberal Canada/Entente should have a higher chance to support PSA, or if USA isn’t doing so well by the time Eddie decides to take a side (perhaps a state-hold count, much like intervention against CSA considers).
-PSA should have legislative agendas/laws to be passed like democratic USA does.
-PSA should start with a mountaineer.
-PSA music is too similar to USA music. Maybe more vocal/pop songs to go with the Hollywood-esque culture?
-A small airfield(s) should be built somewhere in the Rockies air zone. While the Plains can still remain a no fly zone, at least a defensive DeWitt PSA should have some airfields in the rockies to counter enemy air supremacy/bombers.
-If possible, a player should regain foci buffs if returning to a party which has lost an election. (For example, 1937 prog -> 1940 Democrats -> 1944 Prog should regrant prog tree spirits.)
-The Sleepy Lagoon event chain should have more impact on stability/popularity/etc and a choice/forced choice like HUAC does.
-HUAC should be a national spirit.
-While the Republican tree touches it on a bit, there should be more flavor related to film/media, especially given how PSA is a big exporter of it culturally.

Saves:
[PSA Saves.zip](https://github.com/Kaiserreich/Kaiserreich-DH/files/5833524/PSA.Saves.zip)

**Comment by eberronguy** [comment]
You made a very thorough git report, and for that I thank you. 

However this git is for the Darkest Hour version of Kaiserreich, and not the HOI4 version. Here is the link you can use to file the report in the right spot. Thank you very much in advance for bringing these issues to our attention!

https://github.com/Kaiserreich/Kaiserreich-4/issues
