### ISSUE TITLE
Critical error at start (typo)

### ISSUE THREAD

**Issue by BobSemple** [Kaiserreich/Kaiserreich-DH#51]
With the new flavour events, one gets the following error at start:
![DH_error1](https://user-images.githubusercontent.com/73502859/118124342-bcc02300-b3f5-11eb-920a-cc9a004f4eb4.jpg)

Corresponding line from savedebug.txt:
ERROR : Unknown trigger type [governmet] in Mods\Kaiserreich-DH\db\events\Entente\Entente Flavor.txt, line 473!

Please fix the typo. :) (governmet -> government)

**Comment by throwingstones123** [comment]
Thank you for your report, it's quite silly of me to put in the outdated flavour file,will change ASAP
