### ISSUE TITLE
Endonyms and Exonyms

### ISSUE THREAD

**Issue by Galt69** [Kaiserreich/Kaiserreich-DH#53]
<img width="1564" alt="Screen Shot 2021-06-05 at 8 07 27 PM" src="https://user-images.githubusercontent.com/85420017/120908596-c6762880-c639-11eb-9031-53fee9f8dfb3.png">
Endonyms and exonyms are not working properly for me. In this photo, for example, Russia has annexed Ukraine, but Kyiv's name will not change to Kiev. I have tried this with other cities like Brasov/Brassó to make sure that it was not just a one-time mistake. I did not run any other mods with Kaiserreich while testing this. I have also uninstalled and reinstalled the mod, but the problem still persists. What should I do? 
Thanks in advance.

**Comment by throwingstones123** [comment]
Thank you for your report but this repo is for KRDH,please bring your report over to the KR4 Team
