### ISSUE TITLE
Game keeps crashing at specific point

### ISSUE THREAD

**Issue by Deathchair** [Kaiserreich/Kaiserreich-DH#58]
I'm playing as the Fengtian Government and am in the process of invading the Home Islands. I have reached a point where if I advance a single square, the game crashes immediately. I have restarted several times and noted that it is specifically triggered by this action. I don't believe it has to do with the base game because I've tried lowering graphics and it still occurs.

![bild](https://user-images.githubusercontent.com/87996181/127030746-bd214709-391d-4f28-94bd-5f6e7d8ce420.png)

**Comment by throwingstones123** [comment]
Thank you for your report but this is the KRDH repository. Please move your report over to the KR4 issue report repo
