### ISSUE TITLE
Spanish Civil War Bug

### ISSUE THREAD

**Issue by KlyntarKing** [Kaiserreich/Kaiserreich-DH#59]
![Screenshot 2021-07-27 195700](https://user-images.githubusercontent.com/78797068/127380127-f644df32-eff0-475e-8205-6ee4019baea1.png)
CNT annexed the Kingdom at the start of the war and wasn't at war with the Carlists.

**Comment by Maxian25** [comment]
There's an event where SPA can be inherited by either EUS or SPR, but I think that breaks the EUS-SPR conflict since the trigger requires SPA to be at war with EUS to declare on SPR.
