### ISSUE TITLE
Problems with 3 Australasian events.

### ISSUE THREAD

**Issue by KlyntarKing** [Kaiserreich/Kaiserreich-DH#60]
![Screenshot 2021-07-28 162501](https://user-images.githubusercontent.com/78797068/127380426-7d44636c-b882-4df0-b864-8565cf273cf3.png)
![Screenshot 2021-07-28 162546](https://user-images.githubusercontent.com/78797068/127380428-a7cd750f-b2e6-463c-9708-f6dc7159fac4.png)
These 2 Events for Australia meant for the Republic firing even though Australasia is still part of the Empire. I think this happened because I elected Labour and there isn't a check for if the Republic was proclaimed for the events.
![Screenshot 2021-07-28 195055](https://user-images.githubusercontent.com/78797068/127380579-23d19092-cca5-49dc-9c5d-e7b77f7de2c2.png)
The picture for this event is bugged.

**Comment by throwingstones123** [comment]
I've fixed the triggers for these two events, along with the triggers for a few more flavour events meant only for the AFM. Thank you for your report

**Comment by throwingstones123** [comment]
The event pics are also now fixed, thanks again for your report
