### ISSUE TITLE
2 Suggestions for Australasia.

### ISSUE THREAD

**Issue by KlyntarKing** [Kaiserreich/Kaiserreich-DH#61]
![Screenshot 2021-07-27 194637](https://user-images.githubusercontent.com/78797068/127383953-57d73a02-c69a-407f-af5a-ac007d9fd28a.png)
I think the supplies cost for the top 3 options in this event should be reduced to 2000 because 10000 is too high and Australasia also spends daily supplies for ship building projects later.
There should be an event for investing in Marines in the early game that gives you blueprints for marines and creates some Marine units to help you perform Amphibious Assaults.

**Comment by Maxian25** [comment]
I'm thinking dropping initial supplies to 5k, but for options A and B which cost further supplies (around 30k) I'll cut those too.

**Comment by Maxian25** [comment]
As for marines, historically Australia didn't have proper modern marines until ~1941 and that was with the help of the US. Blamey has marine specialty and an event around 1939 to start setting up a marine force could be a thing.
