### ISSUE TITLE
Ottoman revolt state bug

### ISSUE THREAD

**Issue by chiefpotato** [Kaiserreich/Kaiserreich-DH#66]
In my last game anatolian kurdistan and syria both revolted and after reducing the revolt meter to low and then very low and finally none i still got the yellow paradox vanilla revolt sign. However the states had 100 percent (115 in my case since emancipation focus) draftable population. I believe its only caused by revolting states. One last thing i wanna add to ease the develeopers workload is one of the states pf anatolian kurdistan didnt have this issue (erzurum) but kars and van did.

**Comment by KlyntarKing** [comment]
You've reported an issue from Kaiserreich for Hearts of Iron 4 in the wrong place. You should report the issue here instead https://github.com/Kaiserreich/Kaiserreich-4/issues.

**Comment by chiefpotato** [comment]
Oh i'm sorry, should i delete my issue while reporting a new one?

**Comment by KlyntarKing** [comment]
Yes.
