### ISSUE TITLE
Reviving German Empire with AUS does not correctly release Bohemia

### ISSUE THREAD

**Issue by mechu1205** [Kaiserreich/Kaiserreich-DH#67]
![Darkest Hour v 1 05 1 (FGXG)  Mods_Kaiserreich-DH 2021-09-07 오전 12_06_08](https://user-images.githubusercontent.com/50092931/132237273-b7b3d45b-1ecf-4095-9064-54eb9a223172.png)
![Darkest Hour v 1 05 1 (FGXG)  Mods_Kaiserreich-DH 2021-09-07 오전 12_12_13](https://user-images.githubusercontent.com/50092931/132237366-90c2f83e-e140-4bbe-978f-bd679dac949a.png)

As you can see, I still have cores in Bohemia, so the newly released Kingdom of Bohemia only has Prague for herself.

**Comment by Maxian25** [comment]
On it.
