### ISSUE TITLE
Wrong Unit Flag for Khedivate of Egypt (OTT vassal EGY)

### ISSUE THREAD

**Issue by mechu1205** [Kaiserreich/Kaiserreich-DH#68]
![Darkest Hour v 1 05 1 (FGXG)  Mods_Kaiserreich-DH 2021-09-12 오후 3_52_45](https://user-images.githubusercontent.com/50092931/132976906-ce06408f-2831-402b-a0fa-8c234fa8d2cf.png)

When I control EGY units by military control, their flag does not show the correct national flag,
but a transparent one with the red letters "MC" on it.

**Comment by throwingstones123** [comment]
Hmm,im pretty sure this is just an icon to show which units are under your military control so this shouldn't be a bug.

**Comment by mechu1205** [comment]
> Hmm,I'm pretty sure this is just an icon to show which units are under your military control so this shouldn't be a bug.

Units of other nations that are under my military control displays their national flags in that place, so Egypt should be no different.
