### ISSUE TITLE
event script change in commit 1b757e4 causes crash on game start

### ISSUE THREAD

**Issue by mechu1205** [Kaiserreich/Kaiserreich-DH#69]
![GitHub Desktop 2021-09-14 오전 2_31_52](https://user-images.githubusercontent.com/50092931/133130466-b61530fa-a894-4c26-ab40-8f696d468ab2.png)

commit 1b757e4 (Fixed the Socialist Persia bugs) changes 4 lines in db\events\The Middle East\Socialist Persia.txt

One of them, line 1266, causes a crash when you load a game.
```
event = {
id = 59068
random = no
country = U53
picture = "internationale"
style = 2
exists = FRA                    <---------- this line

trigger = {
OR = {
headofstate = 153301
headofstate = 153122
}
}
```
This is because that line is *outside* the `trigger` block.
It should be inside the block, like this:

```
event = {
id = 59068
random = no
country = U53
picture = "internationale"
style = 2

trigger = {
exists = FRA
OR = {
headofstate = 153301
headofstate = 153122
}
}
```

**Comment by Maxian25** [comment]
Thank, adding the fix.
