### ISSUE TITLE
Event 9000 for Libya popping again and again forever

### ISSUE THREAD

**Issue by mechu1205** [Kaiserreich/Kaiserreich-DH#70]
Event 9000 for Libya is the "A Coup in Tripolitania" event.
This is supposed to be the starting point of the LBY event chain of re-establishing its relations with OTT.
However, it will pop again and again under certain conditions, even after OTT triumphs over the Arabs and Libya.

This is what Event 9000 looks like, in `db/events/The Middle East/Libya.txt`.

```
event = {
id = 9000
random = no
country = LBY
persistent = yes              <-- I suspect that this is what enables the event to pop multiple times

trigger = {
puppet = { country = LBY country = OTT  }
atwar = OTT
control = { province = 750 data = LBY }
control = { province = 761 data = LBY }
control = { province = 765 data = LBY }
NOT = {
local_flag = LBY_TRUEPUPPET # set by event Independent Libya in Annexations.txt         <--- Note this flag
}
}
```

`LBY_TRUEPUPPET` flag is set by a follow-up event for the Ottoman Annexation of Libya.
But if Egypt exists, even as your puppet, you can not get the Annexation of Libya event, which means that flag can never be set.
Since the Annexation events for both LBY and EGY can not fire until you finish your war with both of them, this may not be a problem.
But if you have manually liberated Egypt before you annexed Libya (as I have) this would lead to Idris trying his coup over and over again.

Now I know that I should probably always liberate nations via events, but it seems to me that the `persistent = yes` line in Event 9000 should be removed nonetheless.
It seems quite strange that an imprisoned man to launch another coup.
If it was the dev's intention that Idris should (eventually) succeed in toppling the OTT governor, I'd like to suggest instead raising the AI chance of the coup succeeding over failing, which is currently at 70:30.

**Comment by throwingstones123** [comment]
The persistent line has been removed, thank you for the report!
