### ISSUE TITLE
New England (U10) does not properly leave the Entente

### ISSUE THREAD

**Issue by mechu1205** [Kaiserreich/Kaiserreich-DH#71]
U10 has a 10% chance of deciding to leave the Entente in Event 99878 (Canada is trying to set up a military government!),
but even when it does, it won't properly leave the Alliance, as you can see in the screenshot.
(You can see Event 99878 in the Log)

![Darkest Hour v 1 05 1 (YBYG)  Mods_Kaiserreich-DH 2021-09-26 오후 5_29_16](https://user-images.githubusercontent.com/50092931/134800138-84396526-cbf7-48c7-b60f-4706d3c02641.png)

**Comment by throwingstones123** [comment]
I have added a command line so that New England will now leave the Entente when it decides to expulse the Canadians in 99878, thank you again for the report!
