### ISSUE TITLE
Unused OTT_DEFEAT flag: no republican coup after Ottoman defeat?

### ISSUE THREAD

**Issue by mechu1205** [Kaiserreich/Kaiserreich-DH#72]
There are three events that require the OTT_DEFEAT flag to be set.

* Event 5028 in `The Middle East/Hashemite Arabia.txt`: "Mecca to Riyadh Rail"
* Event 5038 in `The Middle East/Hashemite Arabia.txt`: "Leadership over the Cairo Pact?"
* Event 13500 in `The Middle East/Turkey.txt`: "Putschists At Night"

Event 13500 in particular is quite important, as it causes OTT to change tag to TUR.

But it seems that there is no event that actually *sets* the OTT_DEFEAT flag,
which, I believe is supposed to be set by the "Treaty of Damascus/Jersualem" events.

As of now, there is no coup after the Ottomans suffer defeat to the Cairo Pact.
Is this change intentional, and is Event 13500 subject to deprecation?
Or is this just an oversight?

**Comment by throwingstones123** [comment]
I thank you very much for this report. This was a huge oversight on our part and explains why the Turkish Republic hasn't been to coup the Ottoman Empire since the 1.9.3 patch
