### ISSUE TITLE
Kornilov picture is distorted

### ISSUE THREAD

**Issue by mechu1205** [Kaiserreich/Kaiserreich-DH#74]
![kornilov](https://user-images.githubusercontent.com/50092931/135263484-d007ba79-5de9-4466-93a0-1c602bf80443.png)

I've checked the files and the picture `MRUS Kornilov.bmp` is perfectly normal, but for some reason the picture is distorted in-game.
I'm not sure if this is a mod issue, or if there is a problem with my local settings.

**Comment by throwingstones123** [comment]
This usually happens when the portrait isn't scaled to the game's predefined 36x50 size for portraits. Will adjust asap

**Comment by Maxian25** [comment]
I updated several portraits and his was incorrectly sized. I can fix it.
