### ISSUE TITLE
'41 Transport Plane Models with Pictures of Transport Ships

### ISSUE THREAD

**Issue by mechu1205** [Kaiserreich/Kaiserreich-DH#79]
![aus_model_18_3](https://user-images.githubusercontent.com/50092931/136326599-71574b65-5469-4dd2-a320-b46d3c4b8539.jpg)

I've noticed this during an AUS game, but a quick search for `model_18_3` in `gfx/interface/models` revealed that there are multiple countries that use TP pictures for '41 TRA models.
These countries are:
```
U31, U25, U24, U19, U18, U14, U11, HUN, CON, CGX, AUS, GER
```

**Comment by throwingstones123** [comment]
These aren't transport ships though?,if you zoom in you can actually see the propellers

**Comment by Strategia** [comment]
It's an Me 323 Gigant, I can't find the exact image the picture was based on but it's a real plane.
