### ISSUE TITLE
AUS - Exclaves in Czechia after losing to Hungary

### ISSUE THREAD

**Issue by Daru1914** [Kaiserreich/Kaiserreich-DH#91]
I am not sure what was the cause of that, but after losing the war to Hungary that was allied with Czechia(Czechia got annexed by Austria during the war), Austria released an independent Czechia while retaining control over the exclaves of Brno and Tesin.
![image](https://user-images.githubusercontent.com/63430051/157106504-5112f16d-fa85-4274-aff9-8d3065f83e74.png)

**Comment by Maxian25** [comment]
Fixed via adding command to secede the region to Bohemia.
