### ISSUE TITLE
RUS - Possible softlock on Azerbaijan

### ISSUE THREAD

**Issue by Daru1914** [Kaiserreich/Kaiserreich-DH#92]
Decision "The Baku Oil Fields" (id = 750845, russian foreign policy.txt) has an option for Russia to start preparing for a hostile takeover of Azerbaijan. However, the option itself has no timed event to make sure Russia declares war on Azerbaijan, and merely makes the AI prepare for war. If Russia is under control of a human player who picked Realpolitik path, the option is virtually useless, as it does not even give claims, so the text about preparation for war is misleading. 

Furthermore, if the AI does not in the end declare war on Azerbaijan after this event, it remains soft locked from further expansion, since they need control over Georgia and Azerbaijan both to finish the conquest of the Caucasus event chain, making Russia miss out on the Second Weltkrieg.

![image](https://user-images.githubusercontent.com/63430051/157109039-4bbd640b-07f6-4020-8b77-eca648df7a16.png)

**Comment by Maxian25** [comment]
Just fixed.
