### ISSUE TITLE
Typo in Polish Lithuanian Commonwealth event code

### ISSUE THREAD

**Issue by BurgerMeister6** [Kaiserreich/Kaiserreich-DH#93]
I don't really know how to say this but I was playing PLC and I wanted to do the event where you hold a referendum and potentially get some of Ukraine's territory. When I was unable to have the event succeed, I looked stuff up and found many typos in the event document (specifically the ruthenian referendum event chain). Instead of UKR for some of the things, it says KR, which I suspect might be the reason why it was unable to have that event happen.

The exact file location is:
C:\Program Files (x86)\Steam\steamapps\workshop\content\394360\1521695605\events\Polish_Lithuanian_Commonwealth.txt
(~Ln 1400, Col 1)

I'm pretty new to stuff like this so I would be very thankful for any help and I also hope this helps the mod or devs in any way possible.

**Comment by Maxian25** [comment]
This doesn't seem like KRDH, is KR4 bug?

**Comment by BurgerMeister6** [comment]
Oh, sorry, it gets very confusing with how much Kaiserreich stuff there is! I didn’t notice this was for KRDH. Sorry for wasting your time!
