### ISSUE TITLE
Leaders images do not appear

### ISSUE THREAD

**Issue by pedrindasredes** [Kaiserreich/Kaiserreich-DH#97]
I downloaded the mod, but when I went to play the images of the leaders did not appear, none of them.
I looked at the mod files and the images were there but they didn't show up in the game.
Does anyone know what is happening?
ps: I'm playing on the NSB compatible version

**Comment by mountain-zippped** [comment]
This isn't the hoi4 Kaiserreich issue tracker. This issue tracker is for Kaiserreich Darkest Hour. If you need help fixing your game see the KR discord or try a clean install of the mod.
